apiVersion: batch/v1
kind: Job
metadata:
  generateName: ${USER:-default-user}-job-
  labels:
    eidf/user: ${USER:-default-user}
    kueue.x-k8s.io/queue-name: ${QUEUE_NAME:-eidf029ns-user-queue}
    kueue.x-k8s.io/priority-class: ${PRIORITY_CLASS:-short-workload-high-priority}
spec:
  activeDeadlineSeconds: 464256
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        eidf/user: ${USER:-default-user}
    spec:
      containers:
      - name: ${USER:-default-user}-job-container
        image: ${IMAGE_NAME:-nvcr.io/nvidia/pytorch:23.12-py3}
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "--"]
        args:
          - |
            set -ex
            # Start background keep-alive process
            sleep infinity &
            sleeper_pid=$!

            # Setup graceful termination
            shutdown_handler() {
              echo "[INFO] Received termination signal - shutting down"
              kill "$sleeper_pid"
              exit 0
            }
            trap shutdown_handler TERM INT

            # Main command execution
            apt update && \
            apt install -y tmux && \
            cd ~ && \
            cd /workspace && \
            source ${TASK_SCRIPT:-run.sh}

            wait
        env:
        - name: DATASET_DIR
          value: /data/
        - name: MODEL_DIR
          value: /data/model/
        resources:
          limits:
            cpu: ${CPU_NUM:-24}
            memory: ${MEMORY_NUM:-160Gi}
            nvidia.com/gpu: ${GPU_NUM:-1}
        volumeMounts:
        - mountPath: ${MOUNT:-/root/}
          name: ws1
        - mountPath: /workspace
          name: nfs
        - mountPath: /dev/shm
          name: dshm
      restartPolicy: Never
      nodeSelector:
        nvidia.com/gpu.product: ${GPU_PRODUCT:-NVIDIA-H100-80GB-HBM3}
      volumes:
      - name: ws1
        persistentVolumeClaim:
          claimName: ${WORKSPACE_PVC:-default-user-ws4}
      - name: nfs
        nfs:
          path: ${NFS_PATH:-/user/default-user/}
          server: ${NFS_SERVER:-10.24.1.255}
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 160Gi
  ttlSecondsAfterFinished: 604800